SELECT * 
FROM HOUSE h 
WHERE NOT EXISTS
			(SELECT * 
			FROM UNIT u 
			WHERE (u.CAPACITY = 5) 
			AND NOT EXISTS 
					(SELECT * 
					FROM HOUSE h2 
					WHERE h.HOUSENAME = u.HOUSENAME  
					AND u.HOUSENAME = h2.HOUSENAME))